apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: mohammed-addi-mlops:latest
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app
spec:
  selector:
    app: streamlit
  ports:
    - name: web
      protocol: TCP
      port: 8501
      targetPort: 8501
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
